apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: artemis-security-oidc
spec:
  loginModules:
    keycloakLoginModules:
      - name: 'keycloak-broker'
        moduleType: 'directAccess'
        configuration:
          realm: 'artemis-keycloak'
          resource: 'artemis-broker'
          # the url has to point to keycloak service in k8s
          authServerUrl: 'http://keycloak-service.keycloak.svc.cluster.local:8080/'
          useResourceRoleMappings: true
          principalAttribute: 'preferred_username'
          sslRequired: 'none'
          #confidentialPort: 8443
          credentials:
            - key: 'secret'
              value: 'HaDNIDfmkhFyd2i7jPIW5oLaCIZqys0Y'
      - name: 'keycloak-console'
        moduleType: 'bearerToken'
        configuration:
          realm: 'artemis-keycloak'
          resource: 'artemis-console'
          # the url has to point to keycload service in k8s or Ingress
          # this url is used by hawtio and frontend js
          # in case frontend js is outside k8s, ingress must be used
          authServerUrl: 'http://keycloak-service-keycloak.apps.cluster-5wjkd.5wjkd.sandbox1749.opentlc.com/'
          principalAttribute: 'preferred_username'
          useResourceRoleMappings: true
          allowAnyHostName: true
          sslRequired: 'none'
          #confidentialPort: 443
  securityDomains:
    brokerDomain:
      name: 'activemq'
      loginModules:
        - name: 'keycloak-broker'
          flag: 'required'
    consoleDomain:
      name: 'console'
      loginModules:
        - name: 'keycloak-console'
          flag: required
  securitySettings:
    broker:
      - match: 'demo.#'
        # only amq role can consume, guest role can send
        permissions:
        - operationType: 'createDurableQueue'
          roles:
            - 'amq'
            - 'consumer'
        - operationType: 'deleteDurableQueue'
          roles:
            - 'amq'
            - 'consumer'
        - operationType: 'createNonDurableQueue'
          roles:
            - 'amq'
            - 'consumer'
        - operationType: 'deleteNonDurableQueue'
          roles:
            - 'amq'
            - 'consumer'
        - operationType: 'send'
          roles:
            - 'amq'
            - 'producer'
        - operationType: 'consume'
          roles:
            - 'amq'
            - 'consumer'
      - match: 'activemq.management.#'
        permissions:
        - operationType: 'createNonDurableQueue'
          roles:
          - 'amq'
        - operationType: 'createAddress'
          roles:
          - 'amq'
        - operationType: 'consume'
          roles:
          - 'amq'
        - operationType: 'manage'
          roles:
          - 'amq'
        - operationType: 'send'
          roles:
          - 'amq'
    management:
      hawtioRoles:
        - 'amq'
      authorisation:
        roleAccess:
          - domain: 'org.apache.activemq.artemis'
            accessList:
            - method: 'list*'
              roles:
                - 'amq'
            - method: 'sendMessage*'
              roles:
                - 'amq'
            - method: 'browse*'
              roles:
                - 'amq'
