apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: spoke-01-broker
spec:
  adminUser: "admin"
  adminPassword: "admin"
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    journalType: nio
    enableMetricsPlugin: true
    storage:
      size: 500Mi
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "2Gi"
    extraMounts:
      secrets:
        - "oidc-jaas-config"
  acceptors:
    - name: amqp-acceptor
      protocols: amqp
      port: 5672
    - name: amqps-acceptor
      protocols: amqp
      port: 5671
      sslEnabled: true
      sslSecret: broker-tls-secret
      needClientAuth: false
      expose: true
    - name: mqtt-acceptor
      protocols: mqtt
      port: 1833
    - name: mqtts-acceptor
      protocols: mqtt
      port: 8883
      sslEnabled: true
      sslSecret: broker-tls-secret
      needClientAuth: false
      expose: true
#  env:
#    - name: JAVA_ARGS_APPEND
#      value: "-Dhawtio.realm=console -Dhawtio.keycloakEnabled=true -Dhawtio.authenticationEnabled=true -Dhawtio.rolePrincipalClasses=org.apache.activemq.artemis.spi.core.security.jaas.RolePrincipal -Dhawtio.keycloakClientConfig=/amq/extra/secrets/oidc-jaas-config/_keycloak-js-client.json"
  console:
    expose: true
    requireLogin: true
  brokerProperties:
    - "globalMaxSize=1GiB"
    - "clusterConfigurations.my-cluster.messageLoadBalancingType=OFF"

    - "acceptorConfigurations.amqps-acceptor.params.sslAutoReload=true"
    - "acceptorConfigurations.mqtts-acceptor.params.sslAutoReload=true"

    - "connectorConfigurations.hub-01-connector.params.autoStart=true"
    - "connectorConfigurations.hub-01-connector.params.host=hub-01-broker-cores-acceptor-0-svc-rte-artemis.${HUB01_DOMAIN}"
    - "connectorConfigurations.hub-01-connector.params.port=443"
    - "connectorConfigurations.hub-01-connector.params.sslEnabled=true"
    - "connectorConfigurations.hub-01-connector.params.trustStorePath=/etc/artemis-broker-tls-secret-volume/client.ts"
    - "connectorConfigurations.hub-01-connector.params.trustStorePassword=password"

    - "connectorConfigurations.hub-02-connector.params.autoStart=false"
    - "connectorConfigurations.hub-02-connector.params.host=hub-02-broker-coreos-acceptor-0-svc-rte-artemis.${HUB02_DOMAIN}"
    - "connectorConfigurations.hub-02-connector.params.port=443"
    - "connectorConfigurations.hub-02-connector.params.sslEnabled=true"
    - "connectorConfigurations.hub-02-connector.params.trustStorePath=/etc/artemis-broker-tls-secret-volume/client.ts"
    - "connectorConfigurations.hub-02-connector.params.trustStorePassword=password"

    - "federationConfigurations.hub-federation.credentials.user=admin"
    - "federationConfigurations.hub-federation.credentials.password=admin"

    - "federationConfigurations.hub-federation.upstreamConfigurations.hub-upstream.connectionConfiguration.staticConnectors=hub-01-connector,hub-02-connector"
    - "federationConfigurations.hub-federation.upstreamConfigurations.hub-upstream.connectionConfiguration.retryInterval=500"
    - "federationConfigurations.hub-federation.upstreamConfigurations.hub-upstream.connectionConfiguration.retryIntervalMultiplier=2"
    - "federationConfigurations.hub-federation.upstreamConfigurations.hub-upstream.connectionConfiguration.maxRetryInterval=30000"
    - "federationConfigurations.hub-federation.upstreamConfigurations.hub-upstream.connectionConfiguration.circuitBreakerTimeout=30000"
    - "federationConfigurations.hub-federation.upstreamConfigurations.hub-upstream.policyRefs=ny-policy,nj-policy,ct-policy,all-policy"

    - "federationConfigurations.hub-federation.addressPolicies.ny-policy.includes.ny-all.addressMatch=messages.NY.#"
    - "federationConfigurations.hub-federation.addressPolicies.ny-policy.excludes.ny-5603.addressMatch=messages.NY.5603"

    - "federationConfigurations.hub-federation.addressPolicies.nj-policy.includes.nj-all.addressMatch=messages.NJ.#"

    - "federationConfigurations.hub-federation.addressPolicies.ct-policy.includes.ct-all.addressMatch=messages.CT.#"

    - "federationConfigurations.hub-federation.addressPolicies.all-policy.includes.all.addressMatch=messages.ALL.#"
